language: csharp

solution: ./Simple.sln

branches:
  only:
    - master

before_install:
  - wget http://nuget.org/nuget.exe -O ./.nuget/NuGet.exe

install:

  - sudo apt-get install mono-devel mono-dmcs nunit-console make

script:

  - make test
