version: 1.0.{build}

before_build:
- mkdir tools
- nuget install OpenCover -Version 4.6.519 -OutputDirectory tools
- nuget install coveralls.net -Version 0.7.0 -OutputDirectory tools

build_script:
- '"C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe" "Simple.sln" /verbosity:minimal /p:DownloadNuGetExe=true /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"'

skip_commits:

  # Regex for matching commit message
  message: /Update.*\.(md)/

test_script:
- tools\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:path64 -filter:"+[*]*" -target:"C:\Tools\NUnit\bin\nunit-console.exe" -targetargs:"/domain:single  tests\bin\debug\Basic.Katas.Tests.dll" -output:coverage.xml
- tools\coveralls.net.0.7.0\tools\csmacnz.Coveralls.exe --opencover -i coverage.xml --serviceName appveyor --jobId %APPVEYOR_BUILD_NUMBER%

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  
