version: 1.0.{build}
build_script:
- '"C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe" "Simple.sln" /verbosity:minimal /p:DownloadNuGetExe=true /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"'

skip_commits:

  # Regex for matching commit message
  message: /Update.*\.(md)/

test_script:
- tools\coveralls.net.0.7.0\tools\csmacnz.Coveralls.exe --opencover -i coverage.xml --serviceName appveyor --jobId %APPVEYOR_BUILD_NUMBER%
