version: 1.0.{build}
build_script:
- '"C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe" "simple.sln" /verbosity:minimal /p:DownloadNuGetExe=true /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"'
